DROP TABLE IF EXISTS users;

CREATE TABLE users
( id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  widget1 INT(11) NOT NULL DEFAULT 0,
  widget2 INT(11) NOT NULL DEFAULT 0,
  widget3 INT(11) NOT NULL DEFAULT 0,
  widget4 INT(11) NOT NULL DEFAULT 0
);
